id: A47877641
title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
type: translation
pechas:
- I92C1A618
- I4E29442E
- IA2EB4C97
- I61C11994
- I71647E01
source_metadata:
  languages:
  - en
  - de
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:15.925183
  last_modified_at: 2023-01-04 11:55:15.925194
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I92C1A618/9421: 596C
  I4E29442E/3504: 596C
  IA2EB4C97/7C8D: 596C
  I61C11994/742B: 596C
  I71647E01/D4CF: 596C
